"""adding foreignkey for product owner

Revision ID: 640e465a5547
Revises: 28406af6f811
Create Date: 2023-09-14 17:50:21.498173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640e465a5547'
down_revision: Union[str, None] = '28406af6f811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fileDeliverable_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fileDeliverable_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
