"""address and indetification

Revision ID: 6d50d44e28fe
Revises: cbd64d8dc532
Create Date: 2023-09-06 20:23:52.518884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d50d44e28fe'
down_revision: Union[str, None] = 'cbd64d8dc532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserIdentification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nacionality', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('birthDate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userAddress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('isUpdated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('address_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('identification_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'userAddress', ['address_id'], ['id'])
    op.create_foreign_key(None, 'users', 'UserIdentification', ['identification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'identification_id')
    op.drop_column('users', 'address_id')
    op.drop_column('users', 'isUpdated')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_table('userAddress')
    op.drop_table('UserIdentification')
    # ### end Alembic commands ###
