"""nome-da-migration

Revision ID: d300c62c879e
Revises: 
Create Date: 2023-11-03 00:34:44.189454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd300c62c879e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentMethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersAddress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersIdentifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('birthDate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersPreferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('theme', sa.Integer(), nullable=True),
    sa.Column('windowState', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('isUpdated', sa.Boolean(), nullable=True),
    sa.Column('emailVerified', sa.Boolean(), nullable=True),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('identification_id', sa.String(), nullable=True),
    sa.Column('preferences_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['usersAddress.id'], ),
    sa.ForeignKeyConstraint(['identification_id'], ['usersIdentifications.id'], ),
    sa.ForeignKeyConstraint(['preferences_id'], ['usersPreferences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('situation', sa.Integer(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sallerName', sa.String(), nullable=False),
    sa.Column('sallerEmail', sa.String(), nullable=False),
    sa.Column('sallerPhone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount_recluse', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_free', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('marketplace', sa.Boolean(), nullable=False),
    sa.Column('situation', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('situation', sa.Integer(), nullable=False),
    sa.Column('transactionDate', sa.String(), nullable=False),
    sa.Column('aproveDate', sa.String(), nullable=False),
    sa.Column('reimbursementDate', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('wallet_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('paymentMethod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['paymentMethod_id'], ['paymentMethod.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('offers')
    op.drop_table('wallets')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('usersPreferences')
    op.drop_table('usersIdentifications')
    op.drop_table('usersAddress')
    op.drop_table('paymentMethod')
    # ### end Alembic commands ###
