"""database

Revision ID: d53e8cb2012e
Revises: 
Create Date: 2023-09-18 23:50:07.941640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53e8cb2012e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersAddress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersIdentifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('birthDate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersPreferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('theme', sa.Integer(), nullable=True),
    sa.Column('windowState', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('isUpdated', sa.Boolean(), nullable=True),
    sa.Column('emailVerified', sa.Boolean(), nullable=True),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('identification_id', sa.String(), nullable=True),
    sa.Column('preferences_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['usersAddress.id'], ),
    sa.ForeignKeyConstraint(['identification_id'], ['usersIdentifications.id'], ),
    sa.ForeignKeyConstraint(['preferences_id'], ['usersPreferences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sallerName', sa.String(), nullable=False),
    sa.Column('sallerEmail', sa.String(), nullable=False),
    sa.Column('sallerPhone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('usersPreferences')
    op.drop_table('usersIdentifications')
    op.drop_table('usersAddress')
    op.drop_table('categories')
    # ### end Alembic commands ###
